[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.24.2", features = ["full"] }
sweet = { git = "https://github.com/waycrate/sweet", version = "0.4.0" } 
iced = "0.10" 
serde_json = "1.0.140"
