use serde::{Serialize, Deserialize};
use std::collections::BTreeSet;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

#[allow(dead_code)]
pub fn tr(key: &str) -> String {
    match key {
        "app_name" => "App Name".to_string(),
        "apps" => "APPS".to_string(),
        "key_combination" => "Key Combination".to_string(),
        "command" => "Command".to_string(),
        "active" => "Active".to_string(),
        "delete" => "Delete".to_string(),
        "record" => "Record".to_string(),
        "add_hotkey" => "Add Hotkey".to_string(),
        "add_app" => "+ Add App".to_string(),
        "no_apps_available" => "No apps available. Please add an app.".to_string(),
        "swhkd_gui_configurator" => "SWHKD GUI Configurator".to_string(),
        "recording" => "🔴".to_string(),
        "not_recording" => "⎈".to_string(),
        _ => key.to_string(), // Fallback
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Action {
    pub command: String,
    pub active: bool,
    pub layer_id: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Hotkey {
    pub modifiers: BTreeSet<String>,
    pub key: String,
    pub action: Action,
}

impl std::fmt::Display for Hotkey {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        if self.modifiers.is_empty() {
            write!(f, "{}", self.key)
        } else {
            write!(
                f,
                "{} + {}",
                self.modifiers.iter().cloned().collect::<Vec<_>>().join(" + "),
                self.key
            )
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppMode {
    pub name: String,
    pub hotkeys: Vec<Hotkey>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppState {
    pub apps: Vec<AppMode>,
    pub selected_app: usize,
    pub recording_hotkey: Option<usize>,
}

impl Default for AppState {
    fn default() -> Self {
        Self {
            apps: vec![
                AppMode {
                    name: "Terminal Apps".to_string(),
                    hotkeys: vec![
                        Hotkey {
                            modifiers: ["super".to_string()].iter().cloned().collect(),
                            key: "t".to_string(),
                            action: Action {
                                command: "alacritty".to_string(),
                                active: true,
                                layer_id: 0,
                            },
                        }
                    ],
                },
                AppMode {
                    name: "Web Browsers".to_string(),
                    hotkeys: vec![
                        Hotkey {
                            modifiers: ["super".to_string()].iter().cloned().collect(),
                            key: "b".to_string(),
                            action: Action {
                                command: "firefox".to_string(),
                                active: true,
                                layer_id: 0,
                            },
                        }
                    ],
                },
            ],
            selected_app: 0,
            recording_hotkey: None,
        }
    }
}

impl AppState {
    pub fn new() -> Self {
        Self::default()
    }

    /// Save the current state to SWHKD config file
    pub fn save_to_swhkd_config(&self) -> Result<(), Box<dyn std::error::Error>> {
        let config_path = self.get_swhkd_config_path()?;
        let config_content = self.to_swhkd_format();
        
        // Create config directory if it doesn't exist
        if let Some(parent) = config_path.parent() {
            fs::create_dir_all(parent)?;
        }
        
        fs::write(&config_path, config_content)?;
        
        // Signal SWHKD to reload
        self.reload_swhkd()?;
        
        println!("Saved config to: {}", config_path.display());
        Ok(())
    }

    /// Convert AppState to SWHKD config format
    fn to_swhkd_format(&self) -> String {
        let mut config = String::new();
        config.push_str("# SWHKD Configuration generated by GUI\n\n");
        
        for app in &self.apps {
            config.push_str(&format!("# {}\n", app.name));
            for hotkey in &app.hotkeys {
                if hotkey.action.active {
                    let modifiers = if hotkey.modifiers.is_empty() {
                        String::new()
                    } else {
                        format!("{} + ", hotkey.modifiers.iter().cloned().collect::<Vec<_>>().join(" + "))
                    };
                    config.push_str(&format!("{}{}\n", modifiers, hotkey.key));
                    config.push_str(&format!("    {}\n\n", hotkey.action.command));
                }
            }
        }
        
        config
    }

    /// Getting SWHKD config path
    fn get_swhkd_config_path(&self) -> Result<PathBuf, Box<dyn std::error::Error>> {
        let home = dirs::home_dir().ok_or("Could not find home directory")?;
        Ok(home.join(".config").join("swhkd").join("swhkdrc"))
    }

    /// Signalling SWHKD to reload its configuration
    fn reload_swhkd(&self) -> Result<(), Box<dyn std::error::Error>> {
        // Try to send SIGUSR1 to swhkd process to reload
        let output = Command::new("pkill")
            .arg("-USR1")
            .arg("swhkd")
            .output();
            
        match output {
            Ok(_) => println!("Signaled SWHKD to reload"),
            Err(_) => {
                // If pkill fails, try to restart swhkd
                println!("Could not signal SWHKD, trying to restart...");
                let _ = Command::new("systemctl")
                    .arg("--user")
                    .arg("restart")
                    .arg("swhkd")
                    .output();
            }
        }
        
        Ok(())
    }

    /// Loading existing SWHKD config (basic implementation)
    pub fn load_from_swhkd_config(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        let config_path = self.get_swhkd_config_path()?;
        
        if config_path.exists() {
            let content = fs::read_to_string(config_path)?;
            // Basic parsing 
            println!("Loaded existing config: {} lines", content.lines().count());
        }
        
        Ok(())
    }
}

